(function (app) {
    //"use strict";
    var ns = app.namespace("EXCHANGE.enums");

    ns.ApplicationItemTypeEnum = {
        SingleLineTextBox: 0,
        Date: 1,
        Radio: 2,
        DropDown: 3,
        Section: 4,
        Subheader: 5,
        SectionWithDetails: 6,
        MultiLineTextBox: 7,
        Image: 8,
        ProductSummary: 9,
        Hidden: 10,
        Readonly: 11,
        Choice: 12,
        Checkbox: 13,
        BankRoutingNumber: 14,
        SSN: 15,
        MedicareIDNumber: 16,
        Email: 17,
        PhoneNumber: 18,
        AgentScript: 19,
        Computed: 20,
        CarrierPortalURL: 21,
        Zip: 22,
        County: 23,
        State: 24,
        SeparatedDate: 25,
        FirstDate: 26,
        AddressGroup: 27,
        Addr1: 28,
        Addr2: 29,
        City: 30,
        PersonFName: 31,
        PersonLName: 32,
        PersonPhone: 33,
        ConnectionsBook : 34,
        CarriereSignAcknowledgment : 35,
        CarriereSignAgreement : 36
    };

    ns.ApplicationItemTypeNameEnum = {
        SingleLineTextBox: "singleLineTextBox",
        Date: "date",
        Radio: "radio",
        DropDown: "dropdown",
        Section: "section",
        Subheader: "subheader",
        SectionWithDetails: "sectionWithDetails",
        MultiLineTextBox: "multiLineTextBox",
        Image: "image",
        ProductSummary: "productSummary",
        Hidden: "hidden",
        Readonly: "readonly",
        Choice: "choice",
        Checkbox: "checkbox",
        BankRoutingNumber: "bankroutingnumber",
        SSN: "ssn",
        MedicareIDNumber: "medicareidnumber",
        Email: "email",
        PhoneNumber: "phoneNumber",
        AgentScript: "agentscript",
        Computed: "computed",
        CarrierPortalURL: "carrierportalurl",
        Zip: "Zip",
        County: "County",
        State: "State",
        SeparatedDate: "SpDate",
        FirstDate: "FirstDate",
        AddressGroup: "addressGroup",
        Addr1: "addr1",
        Addr2: "addr2",
        City: "City",
        PersonFName: "PersonFName",
        PersonLName: "PersonLName",
        PersonPhone: "PersonPhone",
        ConnectionsBook: "ConnectionsBook",
        CarriereSignAcknowledgment: "carrierEsignAcknowledgment",
        CarriereSignAgreement: "carrierEsignAgreement"

    };

} (EXCHANGE));
